Closes #12 and #16
lsolano/triplex pull request #29
Opened 2022-04-01 02:31 UTC by lsolano

Several improvements. 
closes #12 
closes #16

2022-04-01 03:11 UTC, lsolano reviewed
+1

2025-05-27 13:49 UTC, jcmordan requested changes

2025-06-04 02:33 UTC, lsolano commented on tests/unit/Validations.Tests/ArgumentsFacts/NotNullEmptyOrWhiteSpaceOnly_Facts.cs
> +    // [Test]
Delete old tests, already covered 100% Line and Branch coverage.

2025-06-04 02:33 UTC, lsolano commented on tests/unit/Validations.Tests/ArgumentsFacts/NotNullOrEmptyMessageFacts.cs
> +        // [Test]
Delete old tests, already covered 100% Line and Branch coverage.

2025-06-04 02:33 UTC, lsolano commented on tests/unit/Validations.Tests/ArgumentsFacts/NotNullOrEmptyMessageFacts.cs
> +        // [Test]
Delete old tests, already covered 100% Line and Branch coverage.

2025-06-04 22:16 UTC, merged